// flow-typed signature: 1b705555185e8b776dd112c86a3952b2
// flow-typed version: <<STUB>>/c_vhttps://registry.npmjs.org/@pgleeson/enzyme-adapter-react-16/-/enzyme-adapter-react-16-1.1.7.tgz/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'c' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c/build/index' {
  declare module.exports: any;
}

declare module 'c/build/ReactSixteenAdapter' {
  declare module.exports: any;
}

declare module 'c/src/index' {
  declare module.exports: any;
}

declare module 'c/src/ReactSixteenAdapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c/build/index.js' {
  declare module.exports: $Exports<'c/build/index'>;
}
declare module 'c/build/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'c/build/ReactSixteenAdapter'>;
}
declare module 'c/src/index.js' {
  declare module.exports: $Exports<'c/src/index'>;
}
declare module 'c/src/ReactSixteenAdapter.js' {
  declare module.exports: $Exports<'c/src/ReactSixteenAdapter'>;
}
