// flow-typed signature: ddfd8fcb8be3a06860992e3e61692d84
// flow-typed version: <<STUB>>/d_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd/auto-bind' {
  declare module.exports: any;
}

declare module 'd/lazy' {
  declare module.exports: any;
}

declare module 'd/test/auto-bind' {
  declare module.exports: any;
}

declare module 'd/test/index' {
  declare module.exports: any;
}

declare module 'd/test/lazy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd/auto-bind.js' {
  declare module.exports: $Exports<'d/auto-bind'>;
}
declare module 'd/index' {
  declare module.exports: $Exports<'d'>;
}
declare module 'd/index.js' {
  declare module.exports: $Exports<'d'>;
}
declare module 'd/lazy.js' {
  declare module.exports: $Exports<'d/lazy'>;
}
declare module 'd/test/auto-bind.js' {
  declare module.exports: $Exports<'d/test/auto-bind'>;
}
declare module 'd/test/index.js' {
  declare module.exports: $Exports<'d/test/index'>;
}
declare module 'd/test/lazy.js' {
  declare module.exports: $Exports<'d/test/lazy'>;
}
