// flow-typed signature: 7d4aabc1ad01185c64f1d00ecec19a40
// flow-typed version: <<STUB>>/react-browser-logger_vhttps://github.com/Colour-Full/react-browser-logger.git/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-browser-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-browser-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-browser-logger/dist/index' {
  declare module.exports: any;
}

declare module 'react-browser-logger/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-browser-logger/dist/index.js' {
  declare module.exports: $Exports<'react-browser-logger/dist/index'>;
}
declare module 'react-browser-logger/src/index.js' {
  declare module.exports: $Exports<'react-browser-logger/src/index'>;
}
