// flow-typed signature: e5500f29875ee1f997564d883fee6c0b
// flow-typed version: <<STUB>>/spa-server_vhttps://github.com/Colour-Full/koa-server.git/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spa-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spa-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spa-server/lib/bin/app' {
  declare module.exports: any;
}

declare module 'spa-server/lib/bin/appHtmlMiddleware' {
  declare module.exports: any;
}

declare module 'spa-server/lib/bin/config/index' {
  declare module.exports: any;
}

declare module 'spa-server/lib/bin/server' {
  declare module.exports: any;
}

declare module 'spa-server/lib/index' {
  declare module.exports: any;
}

declare module 'spa-server/mock-consumer-project/dist/public/bundle' {
  declare module.exports: any;
}

declare module 'spa-server/src/bin/app' {
  declare module.exports: any;
}

declare module 'spa-server/src/bin/appHtmlMiddleware' {
  declare module.exports: any;
}

declare module 'spa-server/src/bin/config/__tests__/index' {
  declare module.exports: any;
}

declare module 'spa-server/src/bin/config/index' {
  declare module.exports: any;
}

declare module 'spa-server/src/bin/server' {
  declare module.exports: any;
}

declare module 'spa-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spa-server/lib/bin/app.js' {
  declare module.exports: $Exports<'spa-server/lib/bin/app'>;
}
declare module 'spa-server/lib/bin/appHtmlMiddleware.js' {
  declare module.exports: $Exports<'spa-server/lib/bin/appHtmlMiddleware'>;
}
declare module 'spa-server/lib/bin/config/index.js' {
  declare module.exports: $Exports<'spa-server/lib/bin/config/index'>;
}
declare module 'spa-server/lib/bin/server.js' {
  declare module.exports: $Exports<'spa-server/lib/bin/server'>;
}
declare module 'spa-server/lib/index.js' {
  declare module.exports: $Exports<'spa-server/lib/index'>;
}
declare module 'spa-server/mock-consumer-project/dist/public/bundle.js' {
  declare module.exports: $Exports<'spa-server/mock-consumer-project/dist/public/bundle'>;
}
declare module 'spa-server/src/bin/app.js' {
  declare module.exports: $Exports<'spa-server/src/bin/app'>;
}
declare module 'spa-server/src/bin/appHtmlMiddleware.js' {
  declare module.exports: $Exports<'spa-server/src/bin/appHtmlMiddleware'>;
}
declare module 'spa-server/src/bin/config/__tests__/index.js' {
  declare module.exports: $Exports<'spa-server/src/bin/config/__tests__/index'>;
}
declare module 'spa-server/src/bin/config/index.js' {
  declare module.exports: $Exports<'spa-server/src/bin/config/index'>;
}
declare module 'spa-server/src/bin/server.js' {
  declare module.exports: $Exports<'spa-server/src/bin/server'>;
}
declare module 'spa-server/src/index.js' {
  declare module.exports: $Exports<'spa-server/src/index'>;
}
