// flow-typed signature: d2df77ee3289728c5fa47a75b62db12c
// flow-typed version: <<STUB>>/spa-webpack_vhttps://github.com/Colour-Full/spa-webpack.git/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spa-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spa-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spa-webpack/bin/copy' {
  declare module.exports: any;
}

declare module 'spa-webpack/dist/copy' {
  declare module.exports: any;
}

declare module 'spa-webpack/webpack.dev' {
  declare module.exports: any;
}

declare module 'spa-webpack/webpack.exports' {
  declare module.exports: any;
}

declare module 'spa-webpack/webpack.prod' {
  declare module.exports: any;
}

declare module 'spa-webpack/webpack.shared.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spa-webpack/bin/copy.js' {
  declare module.exports: $Exports<'spa-webpack/bin/copy'>;
}
declare module 'spa-webpack/dist/copy.js' {
  declare module.exports: $Exports<'spa-webpack/dist/copy'>;
}
declare module 'spa-webpack/webpack.dev.js' {
  declare module.exports: $Exports<'spa-webpack/webpack.dev'>;
}
declare module 'spa-webpack/webpack.exports.js' {
  declare module.exports: $Exports<'spa-webpack/webpack.exports'>;
}
declare module 'spa-webpack/webpack.prod.js' {
  declare module.exports: $Exports<'spa-webpack/webpack.prod'>;
}
declare module 'spa-webpack/webpack.shared.config.js' {
  declare module.exports: $Exports<'spa-webpack/webpack.shared.config'>;
}
