// flow-typed signature: 63ef504f62762297aec845b6b6f8ed62
// flow-typed version: <<STUB>>/@atlaskit/css-reset_v^3.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/css-reset' {
  declare module.exports: any;
}

declare module '@atlaskit/page' {
  declare module.exports: any;
}

declare module '@atlaskit/button' {
  declare module.exports: any;
}

declare module '@atlaskit/inline-edit' {
  declare module.exports: any;
}

declare module '@atlaskit/input' {
  declare module.exports: any;
}

declare module '@atlaskit/field-text' {
  declare module.exports: any;
}

declare module '@atlaskit/item' {
  declare module.exports: any;
}
